// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"nunu-layout-chat/internal/handler"
	"nunu-layout-chat/internal/repository"
	"nunu-layout-chat/internal/server"
	"nunu-layout-chat/internal/service"
	"nunu-layout-chat/pkg/app"
	"nunu-layout-chat/pkg/jwt"
	"nunu-layout-chat/pkg/log"
	"nunu-layout-chat/pkg/server/http"
	"nunu-layout-chat/pkg/server/ws"
	"nunu-layout-chat/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	pitaya := server.NewPitaya(logger, viperViper)
	handlerHandler := handler.NewHandler(logger, pitaya)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler)
	job := server.NewJob(logger)
	roomService := service.NewRoomService(serviceService)
	roomHandler := handler.NewRoomHandler(handlerHandler, roomService)
	wsServer := server.NewWebSocketServer(logger, viperViper, pitaya, roomHandler)
	appApp := newApp(httpServer, job, wsServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewRoomService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewRoomHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob, server.NewWebSocketServer)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,
	wsServer *ws.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, job, wsServer), app.WithName("demo-server"))
}
